// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PracticaParcial2.Data;

#nullable disable

namespace PracticaParcial2.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PracticaParcial2.Model.Carrito", b =>
                {
                    b.Property<Guid>("idCarrito")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("cedulaIdentidad")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("codigoBarra")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("idCarrito");

                    b.HasIndex("cedulaIdentidad")
                        .IsUnique();

                    b.ToTable("carritos");
                });

            modelBuilder.Entity("PracticaParcial2.Model.Persona", b =>
                {
                    b.Property<Guid>("cedulaIdentidad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("apellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("cedulaIdentidad");

                    b.ToTable("personas");
                });

            modelBuilder.Entity("PracticaParcial2.Model.Producto", b =>
                {
                    b.Property<Guid>("codigoBarra")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<Guid>("idTipoProducto")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("codigoBarra");

                    b.ToTable("productos");
                });

            modelBuilder.Entity("PracticaParcial2.Model.TipoProducto", b =>
                {
                    b.Property<Guid>("idTipoProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("idTipoProducto");

                    b.ToTable("tipos");
                });

            modelBuilder.Entity("PracticaParcial2.Model.Carrito", b =>
                {
                    b.HasOne("PracticaParcial2.Model.Persona", "personas")
                        .WithOne("carrito")
                        .HasForeignKey("PracticaParcial2.Model.Carrito", "cedulaIdentidad")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("personas");
                });

            modelBuilder.Entity("PracticaParcial2.Model.Producto", b =>
                {
                    b.HasOne("PracticaParcial2.Model.Carrito", null)
                        .WithMany("listaProductos")
                        .HasForeignKey("codigoBarra")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PracticaParcial2.Model.TipoProducto", "tipoProducto")
                        .WithMany("productos")
                        .HasForeignKey("codigoBarra")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("tipoProducto");
                });

            modelBuilder.Entity("PracticaParcial2.Model.Carrito", b =>
                {
                    b.Navigation("listaProductos");
                });

            modelBuilder.Entity("PracticaParcial2.Model.Persona", b =>
                {
                    b.Navigation("carrito")
                        .IsRequired();
                });

            modelBuilder.Entity("PracticaParcial2.Model.TipoProducto", b =>
                {
                    b.Navigation("productos");
                });
#pragma warning restore 612, 618
        }
    }
}
